name: 'Publish flakestry.dev'
description: 'Release flake to flakestry.dev'
inputs:
  version:
    description: 'Version of the flake to be released'
    required: true
  url:  
    description: 'Flakestry URL'
    required: true
    default: 'https://flakestry.dev'
  # allowEvalErrors:
  #   description: 'Allow eval errors'
  #   required: false
  #   default: 'true'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.version }}
    - uses: cachix/install-nix-action@v22
    - shell: bash
      run: |
        nix flake metadata --json > metadata.json 2> metadata.err || true
        nix flake show --json > flake.json 2> flake.err || true

        metadata=$(cat metadata.json || echo null)
        metadata_errors=$(cat metadata.err || echo null)
        outputs=$(cat flake.json || echo null)
        outputs_errors=$(cat flake.err || echo null)

        RESPONSE=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=${{ inputs.url }}")
        OIDC=$(echo $RESPONSE | jq -r '.value')
        README=$(find . -iname "README*" -print -quit)

        nix run nixpkgs#jo metadata="$metadata" metadata_error="$metadata_errors" outputs="$outputs" outputs_errors="$outputs_errors" readme="$README" version="${{ inputs.version }}"> publish.json

        echo "Publishing to ${{ inputs.url }}"
        cat publish.json

        curl --fail-with-body -X POST -H 'Content-Type: application/json' \
             -H "Github-Token: ${{ github.token }}" \
             -H "Authorization: Bearer $OIDC" \
             -d @publish.json \
             ${{ inputs.url }}/api/publish